# Generated by Django 5.1.1 on 2024-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(max_length=50, verbose_name='Product')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción del Producto')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='Foto')),
            ],
        ),
    ]
